# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/


# Site settings
# can be accessed in HTML files via {{ site.title }}, {{ site.email }}, and so on.
title: chaoyihu.github.io
description: >   # this means to ignore newlines until "baseurl:"
  Curiosity is a gift.
email: contact@chaoyifine.com
github_username: chaoyihu

# Build settings
url: "https://chaoyihu.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
 
# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  skin: classic

